### ISSUE TITLE
universal parsing error

### ISSUE THREAD

**Issue by aiwennba** [blechschmidt/massdns#69]
13:04:32,063 [ALERT] brute:36 - 探测超时重新探测中
    answer = resolver.query(domain, 'A')
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/dns/resolver.py", line 900, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 60.00314283370972 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oneforall.py", line 250, in <module>
    fire.Fire(OneForAll)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 237, in run
    self.main()
  File "oneforall.py", line 181, in main
    brute.run()
  File "/Users/elliot/AllFiles/PentestTools/OneForAll/oneforall/brute.py", line 604, in run
    valid_subdomains = self.main(self.domain)
  File "/Users/elliot/AllFiles/PentestTools/OneForAll/oneforall/brute.py", line 555, in main
    self.enable_wildcard = detect_wildcard(domain, ns_ip_list)
  File "/Users/elliot/AllFiles/PentestTools/OneForAll/oneforall/brute.py", line 78, in detect_wildcard
    wildcard = do_query_a(random_subdomain, resolver)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/tenacity/__init__.py", line 311, in wrapped_f
    return self.call(f, *args, **kw)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/tenacity/__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/tenacity/__init__.py", line 350, in iter
    raise retry_exc.reraise()
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/tenacity/__init__.py", line 168, in reraise
    raise self.last_attempt.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/elliot/AllFiles/PythonProject/pentest3env/lib/python3.8/site-packages/tenacity/__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "/Users/elliot/AllFiles/PentestTools/OneForAll/oneforall/brute.py", line 38, in do_query_a
    raise tenacity.TryAgain
tenacity.TryAgain

**Comment by blechschmidt** [comment]
It does not seem like this has to do anything with massdns.
